//! Do not edit this file manually, it is generate by `prisma repo generator`

import _ from 'lodash';
import { PrismaClient, Prisma, Profile, User, Post, Comment } from '@prisma/client';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyRecord = Record<string, any>;

export interface BaseOption<Include, Select> {
  include?: Include;
  select?: Select;
}

export interface Find<Select, Include, Cursor, Order, Distinct>
  extends BaseOption<Include, Select> {
  cursor?: Cursor;
  take?: number;
  skip?: number;
  orderBy?: Prisma.Enumerable<Order>;
  distinct?: Distinct;
}

export const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
});

export const models = _.omit(prisma, [
  '$on',
  '$connect',
  '$disconnect',
  '$use',
  '$executeRaw',
  '$executeRawUnsafe',
  '$queryRaw',
  '$queryRawUnsafe',
  '$transaction',
]);

export const MODELS_NAME = {
  PROFILE: 'profile',
  USER: 'user',
  POST: 'post',
  COMMENT: 'comment',
} as const;

// eslint-disable-next-line @typescript-eslint/ban-types
export type ModelStructure = {
  profile: Profile;
  user: User;
  post: Post;
  comment: Comment;
};

export type ModelName = keyof ModelStructure;

export type ModelScalarFields<T extends keyof ModelStructure> = Prisma.Enumerable<
  keyof ModelStructure[T]
>;

export type ModelDelegate = Prisma.RejectOnNotFound | Prisma.RejectPerOperation | undefined;

export type ModelTypes = {
  profile: {
    Where: Prisma.ProfileWhereInput;
    Select: Prisma.ProfileSelect;
    Include: Prisma.ProfileInclude;
    Create: Prisma.ProfileCreateInput;
    Update: Prisma.ProfileUpdateInput;
    Cursor: Prisma.ProfileWhereUniqueInput;
    Order: Prisma.ProfileOrderByWithRelationInput;
    Delegate: Prisma.ProfileDelegate<ModelDelegate>;
  };
  user: {
    Where: Prisma.UserWhereInput;
    Select: Prisma.UserSelect;
    Include: Prisma.UserInclude;
    Create: Prisma.UserCreateInput;
    Update: Prisma.UserUpdateInput;
    Cursor: Prisma.UserWhereUniqueInput;
    Order: Prisma.UserOrderByWithRelationInput;
    Delegate: Prisma.UserDelegate<ModelDelegate>;
  };
  post: {
    Where: Prisma.PostWhereInput;
    Select: Prisma.PostSelect;
    Include: Prisma.PostInclude;
    Create: Prisma.PostCreateInput;
    Update: Prisma.PostUpdateInput;
    Cursor: Prisma.PostWhereUniqueInput;
    Order: Prisma.PostOrderByWithRelationInput;
    Delegate: Prisma.PostDelegate<ModelDelegate>;
  };
  comment: {
    Where: Prisma.CommentWhereInput;
    Select: Prisma.CommentSelect;
    Include: Prisma.CommentInclude;
    Create: Prisma.CommentCreateInput;
    Update: Prisma.CommentUpdateInput;
    Cursor: Prisma.CommentWhereUniqueInput;
    Order: Prisma.CommentOrderByWithRelationInput;
    Delegate: Prisma.CommentDelegate<ModelDelegate>;
  };
};
